format = """
$username\
$hostname\
$character\
$git_branch\
$git_status\
$git_state\
$cmd_duration\
$line_break\
$python"""

[directory]
style = "fg:#282828 bg:#229FF7"
home_symbol = "☺"
format = " [ $path ]($style) "

[character]
success_symbol = "[ ☺ ](fg:#282828 bg:#D7888B)"
error_symbol = "[ ☹ ](fg:#282828 bg:#C01C28)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "fg:#D7888B bg:#282828"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
